File "c:\Users\Stuart\Python Scripts\scifiRPG\character_creation_funcs.py", line 24, in generate_name
    raise FileNotFoundError(f"Name file for race '{race}' not found: {filepath}")
FileNotFoundError: Name file for race 'Martian' not found: C:\Users\Stuart\Python Scripts\scifiRPG\scifiRPG\data\Names\MartianNames.txt

This problem has happened before. The scifiRPG part of teh filename is duplicated.
The solution is constructing a filepath for names in common.py in the same fashion as this one
BASE_STARTINGLOYALTIES_DIR = get_file_path("data", "Test City", "startingLoyalties")

Iadded this to common.py
BASE_CHARACTERNAMES_DIR = get_file_path("data", "Names")

In loader I changed this function but it needs debugging.
def get_name_file_path(race):
    """
    Constructs the file path for a given race's name file.
    """
    BASE_CHARACTERNAMES_DIR = ("data", "Names")
    filename = f"{race}Names.txt"  # Assuming names are stored as RaceNames.txt
    
    return filename

Does this function even need to be called?
Can character_creation_funcs.py simply call the line in common.py?
